import Head from 'next/head'
import TopHeader from './../src/components/TopHeader/TopHeader';
import MainSection from './../src/components/MainSection/MainSection';
import Navbar from '../src/components/Navbar/Navbar';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         <Navbar></Navbar>
        <TopHeader></TopHeader>
       <MainSection></MainSection>
    </div>
  )
}
